# Generated by Django 4.1.5 on 2023-01-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_requestcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcount',
            old_name='count',
            new_name='requestCount',
        ),
    ]
