# Generated by Django 4.1.5 on 2023-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_rename_count_requestcount_requestcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcount',
            name='requestCount',
            field=models.IntegerField(),
        ),
    ]
